version: 1.0.0.{build}
image: Visual Studio 2019

environment:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

build_script:
- ps: dotnet publish -c Release -r win-x64 Lostark.Loahae/Lostark.Loahae.csproj

after_build:
- ps: >-
    Compress-Archive -Path "Lostark.Loahae\bin\Release\win-x64\publish\*" -DestinationPath "plugin.zip"

    Rename-Item plugin.zip Lostark.Loahae.flowlauncher

artifacts:
    - path: 'Lostark.Loahae.flowlauncher'